spring:
  application:
    name: reday
  profiles:
    default: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-expiration: 30m
  refresh-token-expiration: 14d

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /docs/openapi/REDAY_openapi_v1.yaml
